### ISSUE TITLE
Improve warning messages on cluster summary()

### ISSUE THREAD

**Issue by wleoncio** [tmatta/lsasim#43]
I tried example 6 
```r
set.seed(4388)
n <- c(cnt = 1, sch = 2, stu = 5)
cg <- cluster_gen(n = n, n_X = 10, c_mean = c(0.3, 0.4, 0.5, 0.6, 0.7))
```

Then I tried `summary(cg)`
And got the following warning messages
![image](https://user-images.githubusercontent.com/74199760/119288865-751c7100-bc17-11eb-9114-55e1934901e3.png)

It seems like all three warning messages are the same. What does the error message mean? Does each message indicate an individual warning for each stage? Maybe we could make it more clear to help users understand where they get these warnings (differently)

_Originally posted by @Hugo-v587 in https://github.com/tmatta/lsasim/issues/12#issuecomment-846692343_

**Comment by wleoncio** [comment]
Dear @Hugo-v587,

Which version of lsasim are you using? On 2.0.2.9009 (the latest one on the develop branch) I cannot reproduce the issue. This is my output:

![image](https://user-images.githubusercontent.com/8234768/119933402-535b1b00-bf84-11eb-8705-00769f7a0d83.png)

**Comment by Hugo-v587** [comment]
My package version is 2.0.2.9009. I couldn't reproduce the issue at this time. That's weird...
I got the same output as you had. So it seems like this issue is resolved.

**Comment by wleoncio** [comment]
Alright, thanks for your feedback. Feel free to reopen if you find a way to reproduce it.
